### ISSUE TITLE
Driver panics on exec statement

### ISSUE THREAD

**Issue by vendion** [bmizerany/pq.go#19]
Using Go1 Rc2 and a version of the driver from the over branch that I just cloned today trying to do an insert statement via the sql.Exec function causes the driver to panic.  The stacktrace from Go is as follows:

```
panic: todo

goroutine 3 [running]:
github.com/bmizerany/pq.(*stmt).Exec()
    /home/vendion/gocode/src/github.com/bmizerany/pq/conn.go:356 +0x4c
database/sql.(*DB).exec(0xf84006a880, 0x6719dc, 0xf800000046, 0xf840069600, 0x300000003, ...)
    /usr/local/go/src/pkg/database/sql/sql.go:363 +0x381
database/sql.(*DB).Exec(0xf84006a880, 0x6719dc, 0x65736e6900000046, 0x7f50842fcc70, 0x300000003, ...)
    /usr/local/go/src/pkg/database/sql/sql.go:332 +0xd5
main.getReading()
    /home/vendion/Projects/cerberus/client.go:45 +0x3b7
main.runclient()
    /home/vendion/Projects/cerberus/client.go:29 +0x145
created by main.main
    /home/vendion/Projects/cerberus/cerberus.go:61 +0x54c

goroutine 1 [chan receive]:
main.main()
    /home/vendion/Projects/cerberus/cerberus.go:67 +0x61c

goroutine 2 [syscall]:
created by runtime.main
    /tmp/bindist343577657/go/src/pkg/runtime/proc.c:221

goroutine 4 [syscall]:
syscall.Syscall6()
    /tmp/bindist343577657/go/src/pkg/syscall/asm_linux_amd64.s:40 +0x5
syscall.EpollWait(0xf800000007, 0xf84008b170, 0xa0000000a, 0xffffffff, 0xc, ...)
    /usr/local/go/src/pkg/syscall/zerrors_linux_amd64.go:1781 +0xa1
net.(*pollster).WaitFD(0xf84008b160, 0xf84006a940, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/pkg/net/fd_linux.go:146 +0x110
net.(*pollServer).Run(0xf84006a940, 0x0)
    /usr/local/go/src/pkg/net/fd.go:236 +0xe4
created by net.newPollServer
    /usr/local/go/src/pkg/net/newpollserver.go:35 +0x382
```

As the error is a "todo" I can't tell exactly what is wrong but the line of code that caused this is:

`rows, err := db.Exec("insert into request (id, command, serialnumber) values ($1, $2, $3)", v.Id, v.Command, v.Serial)`

At this point err comes back not nil

**Comment by notedit** [comment]
you should use this new driver:

https://github.com/bmizerany/pq

**Comment by bmizerany** [comment]
Thank you helping. This repo is deprecated. Please see bmizerany/pq. This one is not official, yet, but has less bugs, we think. :) Please help by filing any issues you find or patches.

This is a rewrite of pq.go and takes advantage of the newer goodies in database/sql.

-Blake.

**Comment by vendion** [comment]
Thanks for the heads up on the other repo, I will grab that and do testing with it.

I know @bmizerany and I went through the renaming of the repo on an older bug, but I figured you would rename the repo instead of making a new one.

(I'll go ahead and close this and if have the same issue using the other driver I will file a issue there)

**Comment by bmizerany** [comment]
The problem with renaming is that old code that depends on this repo name will no longer build. I'll leave this one with a message to rename like I did with pat.go.
