### ISSUE TITLE
Error messages seem to have extraneous data

### ISSUE THREAD

**Issue by cthom06** [bmizerany/pq.go#5]
For example:

```
pq: NOTICE (S) NOTICEC00000MCREATE TABLE / PRIMARY KEY will create implicit index "chlgs_pkey" for table "chlgs"Findexcmds.cL439RDefineIndex
```

**Comment by cthom06** [comment]
Obviously it's not a major issue; the entire error is there.

**Comment by bmizerany** [comment]
Honestly, I'm not sure how to interpret that extra data. If you have an idea, please help. I don't like seeing it as much as the next person.
